### ISSUE TITLE
Autofocus username field on login page

### ISSUE THREAD

**Issue by bittebitte** [renyaa/renyaa#11]
The `autofocus=""` attribute should be on the `username` input field so the user doesn't have to click / tab to the login form on page load.

**Comment by willi123yao** [comment]
Noted! Still working on login systems and backend process... Thanks for repoting

**Comment by Jiro-Horikoshi** [comment]
@bittebitte https://github.com/renyaa/renyaa/issues/14

**Comment by willi123yao** [comment]
This should be solved in PR #26
https://github.com/renyaa/renyaa/pull/26
