### ISSUE TITLE
docker: add container for portability

### ISSUE THREAD

**Issue by alexhgian** [renyaa/renyaa#3]
Possibly integrate docker support for the app

**Comment by willi123yao** [comment]
Yeah should get docker. I am also suggesting that we bundle a custom server

**Comment by alexhgian** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Continuous Integration](https://trello.com/c/40tRpJUC/7-continuous-integration)

**Comment by alexhgian** [comment]
We need mariadb now

**Comment by alexhgian** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [MariaDB docker](https://trello.com/c/iFvnI7Py/8-mariadb-docker)
